# imagewriter
# Autogenerated from man page /usr/share/man/man1/imagewriter.1.gz
complete -c imagewriter -s d --description 'Specify a device, for example: /dev/sdc.'
complete -c imagewriter -s f --description 'Specify the file to write.'
complete -c imagewriter -s h -o help --description 'Display help and exit.'
complete -c imagewriter -s k --description 'Operate in "kiosk mode", only listing disks smaller than 200GB.'
complete -c imagewriter -s l --description 'List valid USB devices.'
complete -c imagewriter -s m --description 'Maximize the window.'
complete -c imagewriter -s u --description 'Operate in unsafe mode, listing all disks, not just removable ones.'
complete -c imagewriter -s v --description 'Displays version and author information and exit.'

