// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.network.http.spdy.websockets", false);
user_pref("app.normandy.user_id", "087f344f-2c74-48bd-a299-6a15aad6b3d3");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1566316180);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1566316300);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1566392000);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1566315940);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1566315820);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1566316060);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1566316540);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1566316420);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 1700);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1566315672);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{0910d17a-2d1e-4319-88fb-61ffb947c0fd}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1566230400);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\",\"pinTab\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1566391975467");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1566393779467");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1566391976709");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1566395576709");
user_pref("browser.search.region", "CN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190720144906");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1566331813");
user_pref("browser.slowStartup.averageTime", 5236);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20190720144906");
user_pref("browser.startup.homepage_override.mstone", "68.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1566391972);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1566315682182");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.Manjaro.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "69dac74b56c04a198388b31b4a01c315");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Fri, 09 Aug 2019 09:59:13 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1566316184);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20190720144906");
user_pref("extensions.lastAppVersion", "68.0.1");
user_pref("extensions.lastPlatformVersion", "68.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"a136363e-0ecd-4326-a34f-b2229903465e\",\"screenshots@mozilla.org\":\"1ad639fd-0a4e-4557-b324-0d3a69002df0\",\"webcompat-reporter@mozilla.org\":\"84510e84-55be-417d-a27a-c473f9684242\",\"webcompat@mozilla.org\":\"adcedd0c-e562-457a-9838-f3d8844c2a39\",\"baidu-code-update@mozillaonline.com\":\"16ad958e-5e44-4fa8-ad55-86443386d49c\",\"fxmonitor@mozilla.org\":\"388b8087-3635-4cee-b295-7a4456d56ab3\",\"default-theme@mozilla.org\":\"fdf082d6-fd9d-4a53-94b5-d0ddcb185ed4\",\"google@search.mozilla.org\":\"cdd86e8d-59fa-43fe-9c11-6913629c425a\",\"amazondotcom@search.mozilla.org\":\"ab471223-6d6e-470f-85db-ee566df0f221\",\"bing@search.mozilla.org\":\"7434b3ab-4058-470b-96f3-5646f4468678\",\"ddg@search.mozilla.org\":\"23489fb6-d583-4c15-9dd1-2c06753dc66b\",\"ebay@search.mozilla.org\":\"a1b252d5-625f-45e9-b5b3-1a91ac7dd72a\",\"twitter@search.mozilla.org\":\"a8c29c33-80ee-4b14-8679-cac104090ca7\",\"wikipedia@search.mozilla.org\":\"30626ba1-c011-49d8-a1b7-a451e4432b4b\"}");
user_pref("idle.lastDailyNotification", 1566316707);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1566332036);
user_pref("media.gmp-gmpopenh264.version", "1.8.1");
user_pref("media.gmp-manager.buildID", "20190720144906");
user_pref("media.gmp-manager.lastCheck", 1566332031);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1566316707);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "28882335-dbcb-478b-af24-fa8e050fa5b9");
user_pref("security.sandbox.plugin.tempDirSuffix", "9969e8ee-d30a-4fe5-8dd2-254f848b7434");
user_pref("services.blocklist.addons.checked", 1566287260);
user_pref("services.blocklist.gfx.checked", 1566287260);
user_pref("services.blocklist.onecrl.checked", 1566287260);
user_pref("services.blocklist.pinning.checked", 1566287260);
user_pref("services.blocklist.plugins.checked", 1566287260);
user_pref("services.settings.clock_skew_seconds", 28800);
user_pref("services.settings.last_etag", "\"1566233826256\"");
user_pref("services.settings.last_update_seconds", 1566287260);
user_pref("services.settings.main.language-dictionaries.last_check", 1566287260);
user_pref("services.settings.main.onboarding.last_check", 1566287260);
user_pref("services.settings.main.sites-classification.last_check", 1566287260);
user_pref("services.settings.main.tippytop.last_check", 1566287260);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1566316707);
user_pref("toolkit.startup.last_success", 1566391967);
user_pref("toolkit.telemetry.cachedClientID", "bffb7b35-1415-4409-bedb-aa09053bb4b8");
user_pref("toolkit.telemetry.previousBuildID", "20190720144906");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
